In [1]:
"""
Name: con_tracing.ipynb
Authors: Stephan Meighen-Berger
Example for the tracing of the infection spread
"""
%load_ext autoreload
%autoreload 2

In [2]:
 # General imports
import numpy as np
import matplotlib.pyplot as plt
import sys
from scipy.signal import savgol_filter
from tqdm import tqdm
import pandas as pd

In [3]:
# Adding path to module
sys.path.append("../")
# picture path
PICS = '../pics/'

In [4]:
# Module imports
from contagion import Contagion, config

In [5]:
# Options
config["infected"] = 1
config["simulation length"] = 10
config["average social circle"] = 40
config["population size"] = 100
config["random state"] = np.random.RandomState(1337)

In [6]:
# Creating a contagion object
contagion = Contagion()

In [7]:
 # Storing the solutions
contagion.sim()
stats = pd.DataFrame(contagion.statistics)

In [8]:
stats

is_removed  is_incubation  is_latent  is_infectious  is_infected  \
0           0              0          2              1            3   
1           0              0          3              1            4   
2           0              1          4              1            6   
3           0              1          5              1            7   
4           0              2          6              1            9   
5           1              2          9              0           12   
6           1              4         11              0           16   
7           1              6         13              0           20   
8           1              6         20              0           27   
9           1              6         19              3           29   

   can_infect  is_hospitalized  is_recovered  is_dead  
0           1                0             0        0  
1           1                0             0        0  
2           2                0             0        0  
3           2                0             0        0  
4           3                0             0        0  
5           3                0             0        0  
6           5                0             0        0  
7           7                0             0        0  
8           7                0             0        0  
9          10                0             0        0

In [9]:
contagion.trace_spread

[array([[[47, 75],
         [47, 77],
         [47, 89]]], dtype=int64),
 array([[[47, 21]]], dtype=int64),
 array([[[47, 67],
         [47, 84]]], dtype=int64),
 array([[[47, 33],
         [84, 53]]], dtype=int64),
 array([[[47,  7],
         [84, 49],
         [47, 78]]], dtype=int64),
 array([[[84, 16],
         [84, 45],
         [47, 46],
         [84, 56],
         [47, 76],
         [75, 89],
         [75, 97]]], dtype=int64),
 array([[[47,  2],
         [84,  3],
         [47, 17],
         [75, 23],
         [75, 27],
         [84, 45],
         [47, 57],
         [75, 65],
         [47, 72]]], dtype=int64),
 array([[[27,  8],
         [77, 10],
         [75, 14],
         [47, 31],
         [47, 43],
         [27, 46],
         [75, 60],
         [27, 63],
         [27, 65],
         [27, 66],
         [47, 80],
         [77, 82],
         [47, 85]]], dtype=int64),
 array([[[27,  3],
         [21,  7],
         [33, 11],
         [77, 12],
         [33, 18],
         [27, 21]